"""
Membership model for MongoDB.
Represents user-team relationships with roles.
"""
from datetime import datetime
from typing import Optional
from bson import ObjectId
from enum import Enum


class Role(str, Enum):
    """User roles within a team."""
    ADMIN = "admin"
    SUBMANAGER = "sub_manager"
    MEMBER = "member"
    # IT is a system-wide oversight role that operates above team boundaries.
    # IT members bypass team-level permission checks via require_it_role().
    IT = "it"


class MembershipModel:
    """
    Membership document structure for MongoDB.

    Fields:
        _id: ObjectId (auto-generated by MongoDB)
        user_id: Reference to User ObjectId
        team_id: Reference to Team ObjectId
        role: User's role in the team (admin, sub_manager, member)
        managed_by: Optional ObjectId of Sub-Manager managing this member
        joined_at: Timestamp when user joined the team

    Business Rules:
        - A user can only have one membership per team (unique constraint)
        - Admin: Full permissions across the team
        - Sub-Manager: Manages specific members (tracked via managed_by)
        - Member: Regular team member, may be managed by a Sub-Manager
        - IT: System-wide oversight, bypasses all team-level permission checks
    """

    @staticmethod
    def create_document(
        user_id: ObjectId,
        team_id: ObjectId,
        role: Role,
        managed_by: Optional[ObjectId] = None
    ) -> dict:
        """
        Create a new membership document for insertion into MongoDB.

        Args:
            user_id: ObjectId of the user
            team_id: ObjectId of the team
            role: User's role in the team
            managed_by: Optional ObjectId of Sub-Manager managing this member

        Returns:
            Dictionary representing the membership document
        """
        return {
            "user_id": user_id,
            "team_id": team_id,
            "role": role.value,
            "managed_by": managed_by,
            "joined_at": datetime.utcnow()
        }
