"""
Project model for MongoDB.
Represents high-level initiatives that admins can assign to sub-admins and staff.
"""
from datetime import datetime
from typing import Any, List, Optional
from bson import ObjectId
from enum import Enum


class ProjectStatus(str, Enum):
    """Project status values aligned with the frontend view."""
    ACTIVE = "ACTIVE"
    ON_HOLD = "ON_HOLD"
    COMPLETED = "COMPLETED"


class ProjectModel:
    """
    Project document structure for MongoDB.

    Fields:
        _id: ObjectId (auto-generated by MongoDB)
        title: Project name
        description: Overview/notes
        status: ProjectStatus value
        progress: Integer percentage 0-100
        owner_id: Admin (user) who created the project
        sub_admin_ids: Optional list of sub-admins leading the project
        staff_ids: List of staff member ObjectIds assigned to the project
        team_id: Optional link to a Team document
        created_at / updated_at: Timestamps
    """

    @staticmethod
    def create_document(
        title: str,
        description: str,
        owner_id: ObjectId,
        status: ProjectStatus = ProjectStatus.ACTIVE,
        progress: int = 0,
        sub_admin_ids: Optional[List[Any]] = None,
        staff_ids: Optional[List[Any]] = None,
        team_id: Optional[Any] = None
    ) -> dict:
        """Create a new project document for insertion into MongoDB."""
        now = datetime.utcnow()
        return {
            "title": title,
            "description": description,
            "status": status.value,
            "progress": progress,
            "owner_id": owner_id,
            "sub_admin_ids": sub_admin_ids or [],
            "staff_ids": staff_ids or [],
            "team_id": team_id,
            "created_at": now,
            "updated_at": now
        }