"""
Task model for MongoDB.
Represents tasks/work items in the system.
"""
from datetime import datetime
from bson import ObjectId
from enum import Enum


class TaskStatus(str, Enum):
    """Task status values."""
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    DONE = "done"


class TaskPriority(str, Enum):
    """Task priority levels."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class TaskModel:
    """
    Task document structure for MongoDB.
    
    Fields:
        _id: ObjectId (auto-generated by MongoDB)
        title: Task title
        description: Task details/description
        team_id: Reference to Team ObjectId
        assigned_to: ObjectId of user assigned to this task
        created_by: ObjectId of user who created the task
        status: Task status (todo, in_progress, done)
        priority: Task priority (low, medium, high)
        created_at: Creation timestamp
        updated_at: Last update timestamp
    """
    
    @staticmethod
    def create_document(
        title: str,
        team_id: ObjectId,
        assigned_to: ObjectId,
        created_by: ObjectId,
        description: str = "",
        status: TaskStatus = TaskStatus.TODO,
        priority: TaskPriority = TaskPriority.MEDIUM
    ) -> dict:
        """
        Create a new task document for insertion into MongoDB.
        
        Args:
            title: Task title
            team_id: ObjectId of the team
            assigned_to: ObjectId of the assigned user
            created_by: ObjectId of the user creating the task
            description: Optional task description
            status: Initial task status
            priority: Task priority level
            
        Returns:
            Dictionary representing the task document
        """
        now = datetime.utcnow()
        return {
            "title": title,
            "description": description,
            "team_id": team_id,
            "assigned_to": assigned_to,
            "created_by": created_by,
            "status": status.value,
            "priority": priority.value,
            "created_at": now,
            "updated_at": now
        }
