"""
Team model for MongoDB.
Represents teams/workspaces in the system.
"""
from datetime import datetime
from bson import ObjectId


class TeamModel:
    """
    Team document structure for MongoDB.
    
    Fields:
        _id: ObjectId (auto-generated by MongoDB)
        name: Team name
        description: Optional team description
        created_by: User ID of team creator
        created_at: Creation timestamp
    """
    
    @staticmethod
    def create_document(
        name: str,
        created_by: ObjectId,
        description: str = ""
    ) -> dict:
        """
        Create a new team document for insertion into MongoDB.
        
        Args:
            name: Team name
            created_by: ObjectId of the user creating the team
            description: Optional team description
            
        Returns:
            Dictionary representing the team document
        """
        return {
            "name": name,
            "description": description,
            "created_by": created_by,
            "created_at": datetime.utcnow()
        }
