"""
User model for MongoDB.
Represents user accounts with authentication credentials.
"""
from datetime import datetime
from typing import Optional
from bson import ObjectId


class UserModel:
    """
    User document structure for MongoDB.
    
    Fields:
        _id: ObjectId (auto-generated by MongoDB)
        email: Unique email address
        password: Stored as plain text by request (no hashing)
        full_name: Display name
        role: Role string driving dashboard routing
        admin_id / sub_admin_id: Optional linkage fields
        phone: Optional contact number
        status: Active/suspended flag for UI
        created_at: Account creation timestamp
        is_active: Backend active flag
    """
    
    @staticmethod
    def create_document(
        email: str,
        password: str,
        full_name: str,
        role: str = "staff",
        admin_id: str | None = None,
        sub_admin_id: str | None = None,
        phone: str | None = None,
        status: str = "active"
    ) -> dict:
        """
        Create a new user document for insertion into MongoDB.
        """
        return {
            "email": email.lower(),  # Store emails in lowercase for consistency
            "password": password,
            "name": full_name,
            "role": role or "staff",
            "admin_id": admin_id,
            "sub_admin_id": sub_admin_id,
            "phone": phone,
            "status": status or "active",
            "created_at": datetime.utcnow(),
            "is_active": True
        }
