apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orbit

resources:
  - namespace.yaml
  - backend-config.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml

# Pin image tags per environment, e.g.:
# images:
#   - name: mahmoud416/orbit-backend
#     newTag: v1.0.0
#   - name: mahmoud416/orbit-frontend
#     newTag: v1.0.0
